stages:
  load_data:
    cmd: python src/data/load_data.py --config=params.yaml
    deps:
    - src/data/make_dataset.py
    - src/data/load_data.py
    - data_given/winequality.csv
    outs:
    - data/raw/winequality.csv

