stages:
  load_data:
    cmd: python src/data/load_data.py --config=params.yaml
    deps:
    - src/data/make_dataset.py
    - src/data/load_data.py
    - data_given/winequality.csv
    outs:
    - data/raw/winequality.csv

  split_data:
    cmd: python src/data/split_data.py --config=params.yaml
    deps:
      - src/data/split_data.py
      - data/raw/winequality.csv
    outs:
      - data/processed/train_winequality.csv
      - data/processed/test_winequality.csv

  train_and_evaluate:
    cmd: python src/data/train_and_evaluate.py --config=params.yaml
    deps:
      - data/processed/train_winequality.csv
      - data/processed/test_winequality.csv
      - src/data/train_and_evaluate.py
    params:
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio
#    metrics:
#      - reports/scores.json:
#          cache: false
#      - reports/params.json:
#          cache: false
#    outs:
#      - models/model.joblib
#  log_production_model:
#    cmd: python src/data/log_production_model.py --config=params.yaml
#    deps:
#        - src/data/log_production_model.py

